### PR TITLE
Fixes:#33 design added

### PR DESCRIPTION
**Pull request by j0ker1234**
I'll add more designs on this pr.

### CODE REVIEW

**Comment by j0ker1234** [comment]
@owocki Please review these designs.

**Comment by owocki** [comment]
philosoraptor looks good; is the artwork original or is it just lifted from the meme?  we’re looking for original art
video game looks good
i dont want to put joe’s face on this kudos :) next time, hit me up when you start work on a kudos and i can make sure there are inspiration images attached.  i just added some to the ticket

**Comment by j0ker1234** [comment]
@owocki for the ultimate backer kudos can I mention joe's name in the discription?

**Comment by j0ker1234** [comment]
@owocki I have updated the philosoraptor kudos, removed the ultimate backer one as I was not getting any ideas and added a superhero kudos which a combination of some the most famous superheroes along with a g in the center for gitcoin.

**Comment by j0ker1234** [comment]
@owocki please review this once.

**Comment by owocki** [comment]
awesome :)

**Comment by j0ker1234** [comment]
Thanks

**Comment by owocki** [comment]
live on https://gitcoin.co/kudos/marketplace/

**Pull request merged**
