### PR TITLE
Fixes:#109 spock added

### PR DESCRIPTION
**Pull request by mehul0698**
I have created a svg for the logical kudos. @owocki

### CODE REVIEW

**Comment by owocki** [comment]
can we play with the aesthetic on this one in a second rev?  i think the line weight of the hand is too thick, also it just kind of looks bland.

**Comment by mehul0698** [comment]
@owocki I'll decrease line weight of the hand.It has to be bland as spock is a serious person who does not portray emotion.

**Comment by mehul0698** [comment]
@owocki I have updated the svg. Please review it once.

**Comment by mehul0698** [comment]
@owocki Please review this once and let me know if any changes.

**Comment by mehul0698** [comment]
@owocki is this issue over?

**Comment by mehul0698** [comment]
@owocki I have submitted work on gitcoin. Please review it once and make the payment.

**Comment by owocki** [comment]
you're a great contributor and i'm happy to have you, so will make the payment!

**Comment by owocki** [comment]
https://gitcoin.co/kudos/1839/logical_spock

**Comment by mehul0698** [comment]
@owocki Thank you. If you have any more work just let me know and if you want to do something about monetising the avatar assets I'll be very happy to contribute.

**Pull request merged**
