### PR TITLE
Add Cassette /Pogs /Games kudos

### PR DESCRIPTION
**Pull request by GuistF**
Added a few 90's kudos , These are my first Kudos, I'm very excited! Let me know if everything is ok and if you like it.

### CODE REVIEW

**Comment by GuistF** [comment]
kudos

**Comment by owocki** [comment]
looks awesome!  can you update kudos.yaml with entries for these items too?

**Comment by GuistF** [comment]
sure, I'll do that

**Comment by owocki** [comment]
https://github.com/gitcoinco/kudosbadges/pull/223

**Comment by GuistF** [comment]
the procedures that I performed are right? I am learning and your feedback is important.

**Comment by owocki** [comment]
yes i think this looks good.  let me mint them and comment back.  i can pay you after that too (do you want to own the kudos on the blockchain and recevei the payments when people buy them? or do you want to get paid from the bounty?)

**Comment by owocki** [comment]
live on https://gitcoin.co/kudos/marketplace/?q=

**Comment by GuistF** [comment]
Yes, I saw it right now! For these first models, I will prefer the payment of the reward if not has a problem.

**Comment by GuistF** [comment]
I intend to make some more models for sale. Are there any limits or rules for creating kudos?

**Comment by GuistF** [comment]
I things my descriptions are wrong, the Pogs image has the cassette description...

**Comment by owocki** [comment]
no there are no limits no.  pls make as many as you want (just checkout the instructions in the readme)

@GuistF mind correcting the YAML file and i will burn the old ones and re-mint them?

**Comment by GuistF** [comment]
image: 90_games.svg
- name: Fun time!
  to_address: '0xa6d91F3795f934bb5f703724337f39C0f1a95fD5'
  artist: guistf
  description: Time to remember the best childhood games.
  priceFinney: 10
  numClonesAllowed: 500
  tags:
    - fun
    - tamagotchi
    - Rubiks Cube
    - strategy
    - gameboy
  image: Cassette.svg
- name: let's play some music
  to_address: '0xa6d91F3795f934bb5f703724337f39C0f1a95fD5'
  artist: guistf
  description: For those who like a good classic of the 90's.
  priceFinney: 10
  numClonesAllowed: 500
  tags:
    - music
    - just for fun
    - cassette
    - play
  image: pogs.svg
- name: POGs
  to_address: '0xa6d91F3795f934bb5f703724337f39C0f1a95fD5'
  artist: guistf
  description: Fun images printed making them supremely collectible.
  priceFinney: 10
  numClonesAllowed: 500
  tags:
    - Pac man
    - snakes
    - game
    - School

**Comment by GuistF** [comment]
YAML it's correct now, my mistake, I put the images first. #225

**Comment by owocki** [comment]
@GuistF the last one doesnt have an `image` entry

**Comment by GuistF** [comment]
let me check

**Comment by GuistF** [comment]
I do not understand, do I have to upload the images again?

**Comment by owocki** [comment]
no just correct the YAML you posted an hour ago such that the last kudos entry has an `image` entry, like the other ones

**Comment by owocki** [comment]
http://bits.owocki.com/de2dc4363b70/Image%202019-04-12%20at%2012.30.02%20PM.png

**Comment by GuistF** [comment]
so this is so not correct ?https://github.com/gitcoinco/kudosbadges/pull/225/commits/eb10f557544fc8e382e58a7031fc32b364262741

**Comment by owocki** [comment]
will move the convo over to that PR now.

**Pull request merged**
