### PR TITLE
Requested Logos

### PR DESCRIPTION
**Pull request by yash412**
The consensys and ethereum logo in the retro colorful style as requested! 

lol

ethpl

### CODE REVIEW

**Comment by yash412** [comment]
Do let me know of any changes if you need them.

At 25$/Kudos, you owe me 350$ for the 14 that I made, but 300$ sounds fair as some were pretty easy.

**Comment by yash412** [comment]
[color.zip](https://github.com/gitcoinco/kudosbadges/files/2991141/color.zip)
SVG's of just the logos in case you want to use them elsewhere.

**Comment by yash412** [comment]
Added two new logos from the To-Do List, 

**1 ) Shepherd** 
shepherd

 **2) Saved By The Bell** 
saved_by_bell

**Comment by yash412** [comment]
Assuming you like them, you now owe me 400$ for the 16 Kudos that I made. 
But as I said I would be okay receiving 50$ less as two of them barely took me any time.

**Comment by owocki** [comment]
@yash412 feedback on the consensys logos and ethereum logos:

```
Cheryl Douglass [4:29 PM]
it feels gay pridey to me (edited) 
im not sure why the rainbow apple logo doesnt feel like that
not that i have an issue with gay pride obviously
but it feels like that is its sole purpose

Kevin Owocki [5:03 PM]
hahaha
maybe because we’ve seen it so many times minus that context
any specific instructions i can give the illustrator @cheryl.douglass?

Cheryl Douglass [5:44 PM]
hmm maybe more washed out colors
```

**Comment by owocki** [comment]
> Added two new logos from the To-Do List,

sweet can you please comment directly on those ticketes with the mocks and also move them into the 'designing' column so that our other designers know not to start them

**Comment by yash412** [comment]
@owocki, alright I will try and make it less pridey :') 

Yeah I commented on the individual tickets, I will move them to designing right now.

**Comment by yash412** [comment]
@owocki, sorry but I can't figure out how to transfer to the designing tab? A little help there maybe.

**Comment by owocki** [comment]
@yash412 just upload the svg + img to the ticket i will do the transfer ( i think it might be a github perms thing)

**Comment by yash412** [comment]
@owocki, done.

**Comment by yash412** [comment]
### **New Vs Old** 
Screenshot 2019-03-21 at 5 48 26 PM
Screenshot 2019-03-21 at 5 50 28 PM

@owocki let me know if this is little less pridey :'D

**Comment by yash412** [comment]
Maybe more colors on the consensys logo? 

Screenshot 2019-03-21 at 6 44 27 PM

**Comment by owocki** [comment]
@yash412 looks awesome!  can you update the PR?  lets :shipit: :shipit: :shipit: :shipit:

**Comment by yash412** [comment]
@owocki done :') 
📦 uploaded.

**Comment by yash412** [comment]
@owocki, submitted a total of 17 kudos till now. 
12 from #198 
5 here at #199 ( 2 Apple Style Logos, 2 Saved By The Bell Variants, 1 Shepherd )

**Comment by owocki** [comment]
Thanks!  Whats the latest, how much do I owe you?

**Comment by owocki** [comment]
err, i seee the counts abov.e  is it 17*25=425?

**Comment by yash412** [comment]
@owocki yeah, 18 actually I included the hackathon judge in this PR too! :3 
Thanks!

**Comment by owocki** [comment]
OK; hmm I just sent you 2.2 ETH which is 2.2*140= 308.  so i guess i owe you (17*25)-(2.2*140) = $117 still?

**Comment by yash412** [comment]
@owocki yeah sounds fair actually :')

**Pull request merged**
