### PR TITLE
Added a few 90's kudos

### PR DESCRIPTION
**Pull request by yash412**
Added a few kudos based on the 90s theme. 
Please do check and let me know!

### CODE REVIEW

**Comment by owocki** [comment]
awesome!

**Comment by owocki** [comment]
how much do i owe ya?

**Comment by owocki** [comment]
@yash412 can i get a kudos or two with [the apple-colored-style logo](https://user-images.githubusercontent.com/21294773/54685939-1df74f00-4b29-11e9-9627-7f47a45a372f.jpg) applied to

- [the ethereum logo](https://www.google.com/search?q=ethereum+logo+white&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiYu5b4gpHhAhWb8oMKHYr8AIMQ_AUIDigB&biw=1920&bih=946)
- [consensys logo](https://www.google.com/search?q=consensys+logo&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiiltn9gpHhAhUBiIMKHfc_DrwQ_AUIDigB&biw=1920&bih=946)

**Comment by yash412** [comment]
@owocki sure, I'll get on it.

**Comment by yash412** [comment]
@owocki put up a new PR ( #199 ) with the requested logos! 
Do let me know if you need any changes. 

I made a total of 14 Kudos? That's about 350 dollars. But around 250 should be enough.

**Comment by yash412** [comment]
@owocki I made a new PR ( #199 ) with the requested logos. Do let me know of any changes if you need them. 

At 25$/Kudos, you owe me 350$ for the 14 that I made, but 300$ sounds fair as some were pretty easy.

**Comment by owocki** [comment]
now live at https://gitcoin.co/kudos/marketplace/ !

**Comment by cryptonautica** [comment]
I would check the viewBox or your artboard in illustrator on these because the bottom corner is cut off. 
Screenshot 2019-03-31 at 21 56 52

**Pull request merged**
