### PR TITLE
More designs

### PR DESCRIPTION
**Pull request by j0ker1234**
I have added 3 more kudos. Please review them.

### CODE REVIEW

**Comment by owocki** [comment]
https://www.google.com/search?q=inspector+gadget&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjWhqeW79ngAhWe_YMKHTWECjcQ_AUIDigB&biw=1440&bih=680&dpr=2#imgrc=QHn8LsfCTIE2FM:

https://www.google.com/search?biw=1440&bih=680&tbm=isch&sa=1&ei=C3B1XLraFYK3jgTK2a6gBg&q=lincoln+cartoon&oq=lincoln+cartoon&gs_l=img.3..0l4j0i5i30l6.2993.3656..3768...0.0..0.143.777.2j5......1....1..gws-wiz-img.......0i67.4I09_ov4tN8

can we make sure to only use original art pls?

**Comment by j0ker1234** [comment]
@owocki cool. I'll look into it.

**Comment by j0ker1234** [comment]
@owocki I have updated the lincoln design

**Comment by j0ker1234** [comment]
@owocki I have removed the inspector gadget design as any iteration of it is going to look similar to the cartoon. I have added a narwhal design. Please review and let me know if anymore changes required.

**Comment by j0ker1234** [comment]
@owocki Thanks and from future I'll make sure that all the artworks are original.

**Comment by owocki** [comment]
https://gitcoin.co/kudos/marketplace/

**Pull request merged**
