### PR TITLE
More

### PR DESCRIPTION
**Pull request by j0ker1234**
@owocki I have added 3 more kudos Please review them.

### CODE REVIEW

**Comment by owocki** [comment]
@PixelantDesign @octavioamu what do you think

**Comment by mehul0698** [comment]
@octavioamu I re use the hexagon from other kudos badges but the centre image I make myself or combine 2 or more images together. I'll put the solid bagro6nd for that one. Which one is the smaller one?

**Comment by j0ker1234** [comment]
@octavioamu  I re use the background hexagon from other kudos badges but the centre image I make myself or combine 2 or more eddited images. I'll put a solid background. Which one is the smaller one?

**Comment by octavioamu** [comment]
https://github.com/gitcoinco/kudosbadges/blob/70868be584ecb1ed77e5abf7453c57c045a596f9/images/connector.svg this one is the small one

**Comment by j0ker1234** [comment]
@octavioamu I have made the necessary changes.

**Comment by octavioamu** [comment]
@j0ker1234 the size looks that wasn't change https://github.com/gitcoinco/kudosbadges/blob/b8fd686ee8a5904e01d1bfdf626f1aa6fa70c5f9/images/connector.svg

**Comment by j0ker1234** [comment]
@owocki If anymore changes are required please let me know.

**Comment by j0ker1234** [comment]
@octavioamu If I increase the size anymore the image will go outside the hexagon. If you want I can cut it from edges and increase its size.

**Comment by octavioamu** [comment]
@j0ker1234 compare here and you will understand, the viewbox is set to 110.979 x 128.417 so will be small in the marketplace
https://github.com/gitcoinco/kudosbadges/blob/b8fd686ee8a5904e01d1bfdf626f1aa6fa70c5f9/images/friend.svg

**Comment by j0ker1234** [comment]
@octavioamu I have made that change.

**Comment by j0ker1234** [comment]
@owocki If anymore changes are required please let me know.

**Comment by owocki** [comment]
for me; just resolving the merge conflicts is fine.  @octavioamu any other comments let me know

**Comment by j0ker1234** [comment]
@owocki I have resolved the conflict.

**Comment by j0ker1234** [comment]
@owocki in this pr I submitted 3 designs but you paid me only for 1. Please look into it once

**Comment by j0ker1234** [comment]
@owocki Thanks

**Comment by owocki** [comment]
live on https://gitcoin.co/kudos/marketplace/

**Pull request merged**
