### PR TITLE
Grammar Programmer kudos

### LINKED ISSUE #117: Grammar Programmer
# Title

Grammar Programmer

# Design Inspiration

# Metadata

name: Grammar Programmer
description: Not only did you fix the code, you also fixed that comment that no one noticed!
priceFinney: 50
numClonesAllowed: 1000
tags: 
 - spelling
 - typo
 - programming
 - grammar

# Down Payment

https://etherscan.io/tx/0x40de86e83d0be515b7edcca836009e958dfa6c382933395f35021776f02fbc46

# Gen0 Owner Address

0xf339084e9838281c953F3E812f32a6e145f64BFF

# Other Notes
Sorry it's not still Christmas related... 😅 Make those first.

### PR DESCRIPTION
**Pull request by uivlis**
Fixes #117

### CODE REVIEW

**Comment by owocki** [comment]
thanks @uivlis -- just making sure; is the artwork for this original?

**Comment by uivlis** [comment]
Oh skrank, I forgot about that one. Tons of excuses, I'll pull this off in a moment and I'll submit something new.

**Comment by uivlis** [comment]
@owocki I put up a new one, more aligned with the description of the issue.

**Comment by owocki** [comment]
https://gitcoin.co/kudos/1821/grammar_programmer

**Pull request merged**
